version: '3.8'

services:
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - ./.docker-resources/db:/data/db
    networks:
      - app-network

  redis:
    container_name: redis
    image: redis:5-alpine
    volumes:
      - ./.docker-resources/redis:/data
    restart: unless-stopped
    ports:
      - $REDIS_LOCAL_PORT:$REDIS_EXPOSE_PORT
    networks:
      - app-network

  nodejs:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: nodejs
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./Backend:/app
    networks:
      - app-network

  webserver:
    image: nginx:latest
    container_name: webserver
    depends_on:
      - nodejs
    networks:
      - app-network
    ports:
      - 80:80
      - 6570:6570
      - 6571:6571
      - 6572:6572
    volumes:
      - ./.docker-resources/nginx/production.conf:/etc/nginx/conf.d/default.conf
      - ./Backend:/app
      - ./Frontend:/var/www/management
      - ./ScanPage:/var/www/scanpage

networks:
  app-network:
    driver: bridge